name: NovaPay DevSecOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  frontend-ci:
    name: Frontend CI
    runs-on: self-hosted

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci

      - name: Build Frontend
        working-directory: frontend
        run: npm run build


  backend-ci:
    name: Backend CI
    runs-on: self-hosted

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      - name: Validate Backend Syntax
        working-directory: backend
        run: node --check server.js

      - name: Validate Backend Controllers
        working-directory: backend
        run: |
          shopt -s nullglob
          for file in controllers/*.js; do
            echo "Checking $file"
            node --check "$file"
          done


  docker-build:
    name: Docker Build and Security Scan
    runs-on: self-hosted

    needs:
      - frontend-ci
      - backend-ci

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: docker build -t nitindrathod/novapay-backend:${{ github.sha }} ./backend

      - name: Build Frontend Docker Image
        run: docker build -t nitindrathod/novapay-frontend:${{ github.sha }} ./frontend

      - name: Verify Docker Images
        run: docker images | grep novapay

      - name: Scan Backend Image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: nitindrathod/novapay-backend:${{ github.sha }}
          format: table
          exit-code: "0"
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Scan Frontend Image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: nitindrathod/novapay-frontend:${{ github.sha }}
          format: table
          exit-code: "0"
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Backend Image
        run: docker push nitindrathod/novapay-backend:${{ github.sha }}

      - name: Push Frontend Image
        run: docker push nitindrathod/novapay-frontend:${{ github.sha }}


  ci-success:
    name: CI Success
    runs-on: self-hosted

    needs:
      - frontend-ci
      - backend-ci
      - docker-build

    steps:
      - name: Pipeline Success
        run: |
          echo "======================================"
          echo "NovaPay CI/CD Pipeline Passed"
          echo "Frontend build: PASS"
          echo "Backend validation: PASS"
          echo "Docker build: PASS"
          echo "Trivy security scan: PASS"
          echo "Docker Hub push: PASS"
          echo "======================================"


  deploy:
    name: Deploy to Minikube
    runs-on: self-hosted

    needs:
      - ci-success

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Check Kubernetes
        run: |
          kubectl get nodes
          kubectl get pods

      - name: Update Backend Image
        run: |
          kubectl set image deployment/novapay-backend \
            backend=nitindrathod/novapay-backend:${{ github.sha }}

      - name: Update Frontend Image
        run: |
          kubectl set image deployment/novapay-frontend \
            frontend=nitindrathod/novapay-frontend:${{ github.sha }}

      - name: Restart Deployments
        run: |
          kubectl rollout restart deployment/novapay-backend
          kubectl rollout restart deployment/novapay-frontend

      - name: Wait for Backend
        run: |
          kubectl rollout status deployment/novapay-backend --timeout=180s

      - name: Wait for Frontend
        run: |
          kubectl rollout status deployment/novapay-frontend --timeout=180s

      - name: Verify Deployment
        run: |
          echo "===== PODS ====="
          kubectl get pods

          echo "===== SERVICES ====="
          kubectl get svc
# NovaPay CI/CD
